In [16]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine

In [17]:
DB_PARAMS = {
    "dbname": "testfligoo",
    "user": "admin",
    "password": "password",
    "host": "localhost",
    "port": "5432"
}

In [20]:
def fetch_flight_data():
    try:
        engine = create_engine(f"postgresql+psycopg2://{DB_PARAMS['user']}:{DB_PARAMS['password']}@{DB_PARAMS['host']}:{DB_PARAMS['port']}/{DB_PARAMS['dbname']}")        
        query = "SELECT * FROM testdata;"
        df = pd.read_sql(query, engine)
        return df
    except Exception as e:
        print(f"Error fetching data: {e}")
        return None

In [21]:
df = fetch_flight_data()
df.head()

,id,flight_date,flight_status,departure_airport,departure_timezone,arrival_airport,arrival_timezone,arrival_terminal,airline_name,flight_number
0,1,2025-02-27,active,Shenzhen,Asia - Shanghai,Noibai International,Asia - Ho_Chi_Minh,2,Air China LTD,7977
1,2,2025-02-27,active,Shenzhen,Asia - Shanghai,Suvarnabhumi International,Asia - Bangkok,MAIN,Air China LTD,7979
2,3,2025-02-27,active,Shenzhen,Asia - Shanghai,Suvarnabhumi International,Asia - Bangkok,MAIN,Thai Airways International,6455
3,4,2025-02-27,active,Chu-Bu Centrair International (Central Japan I...,Asia - Tokyo,Shanghai Pudong International,Asia - Shanghai,2,Japan Airlines,6783
4,5,2025-02-27,active,Yantai,Asia - Shanghai,Kansai International,Asia - Tokyo,1,Central Airlines,8871